### ISSUE TITLE
Duration support broken

### ISSUE THREAD

**Issue by Soreil** [Soreil/audio#1]
It is already not there in the AVFormatContext, might be incorrectly setting up the AVIOContext or probing the data.

**Comment by Soreil** [comment]
This dependings on how FFmpeg is built / distributed as well as which format you test on.
I'll have to try some combinations to see what can reliably work and implement the rest myself.

**Comment by bakape** [comment]
So it's some missing --enable flags? I already made a list of all needed libraries to compile ffmpeg with in the meguca README, if that helps.

**Comment by Soreil** [comment]
Nope, I did a full build with all features yesterday and it performed similarly poorly to the regular installs, only on the Raspberry Pi does it really try. There seem to be some default logging levels and also default checking options that differ based on platform. It seems poorly documented and hard to access.
It's clearly not missing features, after all it works just fine when working with files instead of arrays.

**Comment by bakape** [comment]
3.0, right?

**Comment by Soreil** [comment]
Yes

**Comment by bakape** [comment]
Can't you explicitly set log level,  like you can with CLI flags?

**Comment by Soreil** [comment]
Probably, I'll give it a shot when I get back to it.

**Comment by Soreil** [comment]
That didn't really help, I wish there was documentation.

**Comment by bakape** [comment]
So you set https://ffmpeg.org/doxygen/2.5/group__lavu__log.html#ga1fd32c74db581e3e2e7f35d277bb1e24 to AV_LOG_ERROR and nothing happened?

**Comment by Soreil** [comment]
All the way up to verbose, it reports success. I haven't touched it this week because other work, I think I know how to trick it.
